name: platemate_user
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter_svg: ^2.0.4
  get: ^4.3.8
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.8
  carousel_slider: ^4.0.0
  device_info: ^2.0.0
#  firebase_messaging: ^9.1.3
  sms_autofill: ^2.0.0
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^5.0.6
  sign_in_with_apple: ^3.3.0
  file_picker: ^5.2.1
  flutter_contacts: ^1.1.5
  syncfusion_flutter_datepicker: ^20.3.56
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  webview_flutter: ^3.0.1
  socket_io_client: ^1.0.1
  flutter_google_places: ^0.3.0
  pie_chart: ^5.3.2
  timeago: ^3.3.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  charts_flutter_new: ^0.12.0
  url_launcher: ^6.1.7
  flutter_local_notifications: ^13.0.0
  path_drawing: ^1.0.1
  scan: ^1.6.0
  razorpay_flutter: ^1.3.4


#dependency_override:
#  http_parser: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  #flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
